### ISSUE TITLE
can't compile example code with VS2019

### ISSUE THREAD

**Issue by cemunal** [reverseame/Secure_Socket#1]
hi,

thanks for crypto++ project and Secure Socket, firstly.
i am able to compile crypto++ with pem module under VS2019 (i am using git variants and compiled both like release x86 and x64).

and i want to compile example codes in this repository but not succeed. here are some details:

tried to compile "client.cpp" with settings like release x64 and output from VS2019:

**Build started...
1>------ Build started: Project: client64, Configuration: Release x64 ------
1>client64.cpp
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(141,17): error C3646: 'secure_send': unknown override specifier
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(141,28): error C2059: syntax error: '('
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(141,78): error C2238: unexpected token(s) preceding ';'
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(159,17): error C3646: 'secure_recv': unknown override specifier
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(159,28): error C2059: syntax error: '('
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(159,78): error C2238: unexpected token(s) preceding ';'
1>C:\Users\ahertery\source\repos\client64\client64\client64.cpp(25,34): error C2039: 'secure_recv': is not a member of 'Secure_Socket'
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(94): message : see declaration of 'Secure_Socket'
1>C:\Users\ahertery\source\repos\client64\client64\client64.cpp(29,53): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>C:\Users\ahertery\source\repos\client64\client64\client64.cpp(30,13): error C2039: 'secure_send': is not a member of 'Secure_Socket'
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(94): message : see declaration of 'Secure_Socket'
1>C:\Users\ahertery\source\repos\client64\client64\client64.cpp(32,30): error C2039: 'secure_recv': is not a member of 'Secure_Socket'
1>C:\Users\ahertery\Desktop\Secure_Socket\src\Secure_Socket.hpp(94): message : see declaration of 'Secure_Socket'
1>Done building project "client64.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========**

i also tried with settings release x86 and the results are the same.

PS: i am also new with programming and VS2019 so maybe i am doing something wrong.

**Comment by cemunal** [comment]
May be not with VS2019 but I am able to compile 32-bit Windows binaries with mingw-w64 under Kali Linux. Here are steps:

- make CXX=/usr/bin/i686-w64-mingw32-g++
- sudo make install
- i686-w64-mingw32-g++ -O3 client.cpp ../src/Secure_Socket.cpp --std=c++11 -I/usr/local/include/cryptopp -L/usr/local/lib -lcryptopp -lws2_32 -static-libstdc++ -static-libgcc -static -o client.exe

and the fixes on this step :)

- Change the lines "BaseTsd.h" in "Secure_Socket.hpp" and "Key.hpp" files like "basetsd.h".
- Delete the lines "typedef SSIZE_T ssize_t" in "Secure_Socket.hpp" and "Key.hpp" files.

and again:

- i686-w64-mingw32-g++ -O3 client.cpp ../src/Secure_Socket.cpp --std=c++11 -I/usr/local/include/cryptopp -L/usr/local/lib -lcryptopp -lws2_32 -static-libstdc++ -static-libgcc -static -o client.exe

and our client.exe is ready to use :)

**Comment by ricardojrdez** [comment]
That's great. Yes, the official support of this tool is using the GCC compiler. Then I close the issue, thanks.
